# Generated by Django 2.1.5 on 2021-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_name_preface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name_preface',
            field=models.CharField(choices=[('Miss', 'Miss'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Dr', 'Dr')], default='', max_length=30),
        ),
    ]
