# Generated by Django 2.1.5 on 2021-03-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20210310_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='name_preface',
            field=models.CharField(choices=[('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Miss', 'Miss'), ('Dr', 'Dr')], default='', max_length=30),
        ),
    ]
