# Generated by Django 2.0.7 on 2021-03-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(max_length=60)),
                ('username', models.CharField(default='', max_length=60)),
            ],
        ),
    ]
