# Generated by Django 2.1.5 on 2021-03-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name_preface',
            field=models.CharField(choices=[('Dr', 'Dr'), ('Mrs', 'Mrs'), ('Mr', 'Mr'), ('Miss', 'Miss')], default='', max_length=30),
        ),
    ]
